from django.conf.urls import url
from aquaponics.charts import ph, amonia, nitrite, nitrate, simple
from .views import (
	index,
	forms,
	review,
	fishform,
	review_h,
	harvestform,
	planttype_frm,
	fishtype_frm,
	forms_detail,
	fish_detail,
	schedulefrm,
    schedules,
    deletesched,
    viewshed,
    task,
    taskfrm,
    testwater,
    watergraph,
    systemnotes,
    viewnote,
    editnote,
    deletenote,
    editcrop,
    editfish,
)


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^form/$', forms, name='forms'),
    url(r'^fish/$', fishform, name='fishform'),
    url(r'^plant/$', review, name='review'),
    url(r'^cropdetail/(?P<id>\d+)/$', forms_detail, name='forms_detail'),
    url(r'^cropdetail/(?P<id>\d+)/editcrops/$', editcrop, name='editcrop'),
    url(r'^fishdetail/(?P<id>\d+)/$', fish_detail, name='fish_detail'),
    url(r'^fishdetail/(?P<id>\d+)/editfishes/$', editfish, name='editfish'),
    url(r'^harvest/$', review_h, name='review_h'),
    url(r'^harvestfrm/$', harvestform, name='harvestform'),
    url(r'^planttypfrm/$', planttype_frm, name='planttypefrm'),
    url(r'^fishtypfrm/$', fishtype_frm, name='fishtypefrm'),
    url(r'^charts/simple.png$', simple, name='simple'),
    url(r'^schedulfrm/(?P<id>\d+)/scheduleform$', schedulefrm, name='schedulefrm'),
    url(r'^schedule/$', schedules, name='schedules'),
    url(r'^tasks/$', task, name='tasks'),
    url(r'^taskfrm/(?P<id>\d+)/$', taskfrm, name='taskfrm'),
    url(r'^water/$', testwater, name='testwater'),
    url(r'^charts/ph.jpg$', ph, name='ph'),
    url(r'^charts/amonia.png$', amonia, name='amonia'),
    url(r'^charts/nitrite.png$', nitrite, name='nitrite'),
    url(r'^charts/nitrate.png$', nitrate, name='nitrate'),
    url(r'^watergraphs/$', watergraph, name='watergraph'),
    url(r'^notes/$', systemnotes, name='systemnotes'),
    url(r'^viewnotes/(?P<id>\d+)/$', viewnote, name='viewnotes'),
    url(r'^viewnotes/(?P<id>\d+)/editnotes/$', editnote, name='editnote'),
    url(r'^viewnotes/(?P<id>\d+)/deletenotes/$', deletenote, name='deletenote'),
    url(r'^schedulfrm/(?P<id>\d+)/deletescheds/$', deletesched, name='deletesched'),
    url(r'^viewshed/(?P<id>\d+)/scheduleform$', schedulefrm, name='schedulefrm'),
    url(r'^viewshed/(?P<id>\d+)/$', viewshed, name='viewshed'),
    url(r'^viewshed/(?P<id>\d+)/deletescheds/$', deletesched, name='deletesched'),

]

