# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('batch', models.IntegerField()),
                ('spawn_amount', models.IntegerField()),
                ('spawn_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_name', models.CharField(max_length=100)),
                ('harvest_amount', models.IntegerField()),
                ('reap', models.DateField(blank=True, null=True)),
                ('harvest_complete', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('fish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aquaponics.fish')),
            ],
        ),
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('plant_date', models.DateField(verbose_name='Date Planted')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='plant_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='planttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquaponics.plant_type'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aquaponics.plant'),
        ),
    ]
