# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='harvest_amount',
            new_name='amount_reaped',
        ),
        migrations.RenameField(
            model_name='harvest',
            old_name='reap',
            new_name='reap_date',
        ),
    ]
