# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0003_fish_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='planttype',
            new_name='plant_type',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='type',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='plant_name',
        ),
        migrations.AddField(
            model_name='fish',
            name='comment',
            field=models.TextField(default='Testing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fish',
            name='fish_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='aquaponics.fish_type'),
            preserve_default=False,
        ),
    ]
