# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-12 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0004_auto_20170212_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='harvest_name',
        ),
    ]
