# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0005_remove_harvest_harvest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='harvest_complete',
            field=models.DateField(blank=True, null=True),
        ),
    ]
