# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0006_auto_20170212_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='crop',
            field=models.CharField(default='one', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='crop',
            field=models.CharField(default='one', max_length=4),
            preserve_default=False,
        ),
    ]
