# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0008_auto_20170212_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='comment',
            field=models.TextField(max_length=50),
        ),
    ]
