# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0011_auto_20170217_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish_type',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant_type',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
