# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0012_auto_20170218_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish_type',
            old_name='name',
            new_name='fish_name',
        ),
    ]
