# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 01:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0013_auto_20170316_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_time',
            field=models.TimeField(default=datetime.datetime(2017, 5, 23, 1, 46, 19, 923115, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
