# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-05 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0014_plant_plant_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('dates', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_time',
            field=models.TimeField(verbose_name='Time Planted'),
        ),
    ]
