# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 23:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0015_auto_20171004_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='dates',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 10, 23, 57, 17, 681798, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
