# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0016_auto_20171010_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
