# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0017_auto_20171104_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='task_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 22, 6, 9, 551888, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
