# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0018_auto_20171111_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='task_date',
            field=models.DateField(editable=False),
        ),
    ]
