# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0020_auto_20171115_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='task_date',
            field=models.DateField(editable=False),
        ),
    ]
