# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0022_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
