# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0024_auto_20171118_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(auto_now_add=True)),
                ('ph', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('amonia', models.IntegerField(default=0)),
                ('nitrite', models.IntegerField(default=0)),
                ('nitrate', models.IntegerField(default=0)),
            ],
        ),
    ]
