# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0026_auto_20171203_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='ph',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
