# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0029_auto_20171203_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='amonia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='testing',
            name='nitrate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='testing',
            name='nitrite',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
