# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0034_auto_20171209_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='amonia',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=5, null=True),
        ),
    ]
