# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0036_auto_20171209_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='nitrite',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
