# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0037_auto_20171209_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='completed',
            field=models.NullBooleanField(default=False),
        ),
    ]
