# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0038_auto_20171209_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
