# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0040_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 1, 7, 0, 1, 45, 788554, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
