# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-21 22:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0041_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
