# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-03 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0002_fish_type_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=15)),
                ('batch', models.IntegerField()),
                ('spawn_amount', models.IntegerField()),
                ('spawn_date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('fish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquaponics.fish_type')),
            ],
        ),
        migrations.CreateModel(
            name='harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_reaped', models.IntegerField()),
                ('reap_date', models.DateField(blank=True, null=True)),
                ('harvest_complete', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('fish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aquaponics.fish')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aquaponics.plant')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('task_date', models.DateField(editable=False)),
                ('duration', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquaponics.tasks'),
        ),
    ]
