# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-03 04:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaponics', '0003_auto_20190803_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('notes', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(auto_now_add=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('amonia', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('nitrite', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('nitrate', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
            ],
        ),
    ]
